# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Semillero Internacional de Talentos
email: sitalentos2022@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Semillero Internacional de Talentos en Colombia: Empoderamos a niños vulnerables con programas educativos y artísticos. Asociaciones estratégicas con empresas para transformar vidas y fortalecer comunidades.
baseurl: "/sitalentos" # the subpath of your site, e.g. /blog
url: "https://ethx42.github.io" # the base hostname & protocol for your site, e.g. http://example.com
whatsapp_number: https://wa.me/573143731720?text=%C2%A1Hola%20%21+Quiero+saber+más+sobre+Semillero+Internacional+de+Talentos+y+cómo+puedo+ayudar+a+los+niños.%20%C2%BFMe+cuentan+más%3F
instagram_username:  sitalentos14
facebook_username:  100090322849458&mibextid=LQQJ4d

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
